fist_name = input("What is your first name? ")
last_name = input("What is your last name? ")
birth_year = input('hello ' + fist_name + " " + last_name + ' what year were you born? ')
age = 2022 - int(birth_year)
print("you should be about " + age + "years old.")